language: node_js
node_js:
  - 13

services:
  - docker

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed benlagrange/udagram-api-feed:v1
  - docker tag udagram-api-user  benlagrange/udagram-api-user:v1
  - docker tag udagram-frontend benlagrange/udagram-frontend:v1
  - docker tag reverseproxy benlagrange/reverseproxy:v1
# Do similar for other three images

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push benlagrange/udagram-api-feed:v1
- docker push benlagrange/udagram-api-user:v1
- docker push benlagrange/udagram-frontend:v1
- docker push benlagrange/reverseproxy:v1
# Do similar for other three images
