apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
    service: backend-user
spec:    
  ports:
  - port: 8080
    protocol: TCP
  selector:
    service: backend-user
