apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    service: backend-user
    app: backend-user
spec:    
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: backend-user
    app: backend-user