apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: backend-feed
    service: backend-feed
spec:    
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: backend-feed
  type: ClusterIP
status:
  loadBalancer: {}
