apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  labels:
    service: frontend
    app: frontend
spec:    
  ports:
  - name: http
    port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    service: frontend
    app: frontend
